import { Router } from "express";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = Router();
const LETTERS = "ABCDEFGH";

function buildClip(clipId, index, ratio, mode, originalUrl, originalSlug) {
  const name = `Clip ${LETTERS[index] || index}`;
  // Use the real file slug generated by the worker, or fall back to an identifier string
  const fileSlug = originalSlug || `${clipId}.mp4`;
  
  return {
    id: clipId,
    name,
    duration: "0:08",
    ratio,
    mode,
    // Provide a route endpoint mapped directly to our download stream utility handler down below
    downloadUrl: `/api/download/${fileSlug}`,
    url: originalUrl || `/outputs/${fileSlug}`
  };
}

// POST /api/export
router.post("/export", (req, res) => {
  const { jobId, clipIds, ratio, mode } = req.body || {};
  if (!jobId || !Array.isArray(clipIds) || clipIds.length === 0) {
    return res.status(400).json({ error: "jobId and clipIds are required" });
  }
  
  // In a real database scenario, you would look up the specific clip matching the id to grab its real url metadata.
  // For the active session, we format the data objects dynamically using matching configurations.
  const clips = clipIds.map((id, i) => {
    const fileSlug = `${jobId}_clip1.mp4`; 
    return buildClip(id, i, ratio, mode, `/outputs/${fileSlug}`, fileSlug);
  });
  
  res.json({ clips });
});

// POST /api/reexport
router.post("/reexport", (req, res) => {
  const { jobId, clipIds, ratio, mode } = req.body || {};
  if (!jobId || !Array.isArray(clipIds)) {
    return res.status(400).json({ error: "jobId and clipIds are required" });
  }
  const clips = clipIds.map((id, i) => {
    const fileSlug = `${jobId}_clip1.mp4`;
    return buildClip(id, i, ratio, mode || "auto", `/outputs/${fileSlug}`, fileSlug);
  });
  res.json({ clips });
});

// GET /api/download/:fileName — Streams the physical binary MP4 asset directly down to users
router.get("/download/:fileName", (req, res) => {
  const { fileName } = req.params;
  // Resolve the absolute route pointing explicitly inside your permanent outputs disk folder space
  const filePath = path.join(__dirname, "..", "outputs", fileName);

  res.download(filePath, fileName, (err) => {
    if (err) {
      if (!res.headersSent) {
        res.status(404).json({ error: "Requested asset could not be located on the server filesystem." });
      }
    }
  });
});

export default router;