import { Router } from "express";
import path from "path";
import { fileURLToPath } from "url";
import { getJobById } from "../jobStore.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = Router();
const LETTERS = "ABCDEFGH";

function buildClip(clipId, index, ratio, mode, originalUrl, originalSlug) {
  const name = `Clip ${LETTERS[index] || index}`;
  // Use the real file slug generated by the worker, or fall back to an identifier string
  const fileSlug = originalSlug || `${clipId}.mp4`;

  return {
    id: clipId,
    name,
    duration: "0:08",
    ratio,
    mode,
    // Provide a route endpoint mapped directly to our download stream utility handler down below
    downloadUrl: `/api/download/${fileSlug}`,
    url: originalUrl || `/outputs/${fileSlug}`,
  };
}

// Resolve the real output file for a clip id from the in-memory job store.
// This is what fixes the old bug where every clip pointed at `_clip1.mp4`.
function resolveClip(job, id, index, fallbackPrefix) {
  const match = job?.candidates?.find((c) => c.id === id);
  const fileSlug = match?.fileSlug || `${fallbackPrefix}_clip${index + 1}.mp4`;
  return { fileSlug, url: match?.url || `/outputs/${fileSlug}` };
}

// POST /api/export
router.post("/export", (req, res) => {
  const { jobId, clipIds, ratio } = req.body || {};
  if (!jobId || !Array.isArray(clipIds) || clipIds.length === 0) {
    return res.status(400).json({ error: "jobId and clipIds are required" });
  }

  const job = getJobById(jobId);
  const clips = clipIds.map((id, i) => {
    const { fileSlug, url } = resolveClip(job, id, i, jobId);
    return buildClip(id, i, ratio, "editor", url, fileSlug);
  });

  res.json({ clips });
});

// POST /api/reexport
// Note: re-labels clips with a new ratio. Re-cropping each clip would need a
// separate FFmpeg pass per clip; that's tracked separately and not done here.
router.post("/reexport", (req, res) => {
  const { jobId, clipIds, ratio } = req.body || {};
  if (!jobId || !Array.isArray(clipIds)) {
    return res.status(400).json({ error: "jobId and clipIds are required" });
  }

  const job = getJobById(jobId);
  const clips = clipIds.map((id, i) => {
    const { fileSlug, url } = resolveClip(job, id, i, jobId);
    return buildClip(id, i, ratio, "editor", url, fileSlug);
  });
  res.json({ clips });
});

// GET /api/download/:fileName — Streams the physical binary MP4 asset directly down to users
router.get("/download/:fileName", (req, res) => {
  const { fileName } = req.params;
  // Resolve the absolute route pointing explicitly inside your permanent outputs disk folder space
  const filePath = path.join(__dirname, "..", "outputs", fileName);

  res.download(filePath, fileName, (err) => {
    if (err) {
      if (!res.headersSent) {
        res.status(404).json({ error: "Requested asset could not be located on the server filesystem." });
      }
    }
  });
});

export default router;
