import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useSession } from "../lib/SessionContext";
import { api } from "../lib/api";

const STEP_LABELS = [
  "Transcribing audio",
  "Scoring highlight moments",
  "Applying zooms and captions",
  "Rendering options",
];

export default function Processing() {
  const navigate = useNavigate();
  const { jobId, fetchCandidatesForJob } = useSession();
  const [stepIndex, setStepIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState(null); // Track failures explicitly
  const pollRef = useRef(null);

  useEffect(() => {
    if (!jobId) {
      navigate("/configure");
      return;
    }

    pollRef.current = setInterval(async () => {
      try {
        const status = await api.getJobStatus(jobId);
        
        // 1. Handle explicit backend job failures (e.g. FFmpeg crashed)
        if (status.status === "error") {
          clearInterval(pollRef.current);
          setError("The video processing job failed on the server. The video format might be unsupported or too large.");
          return;
        }

        setStepIndex(status.stepIndex);
        setProgress(status.progress);

        // 2. Handle successful completion
        if (status.status === "done") {
          clearInterval(pollRef.current);
          try {
            await fetchCandidatesForJob(jobId);
            navigate("/select");
          } catch (fetchErr) {
            setError("Failed to fetch the clips generated by the server.");
          }
        }
      } catch (networkErr) {
        // 3. Handle network dropouts or Render spinning down
        clearInterval(pollRef.current);
        setError("Lost connection to the processing server. Please check your network or try again.");
      }
    }, 1000); // Polling every 1 second is plenty and lighter on the server

    return () => clearInterval(pollRef.current);
  }, [jobId, navigate, fetchCandidatesForJob]);

  return (
    <div className="max-w-md mx-auto px-8 py-20 text-center">
      <p className="font-mono text-xs uppercase tracking-widest text-accent-2 mb-2">step 02</p>
      <h1 className="font-display font-bold text-2xl mb-8">
        {error ? "Processing Stalled" : "Finding your clips"}
      </h1>

      {/* If there's an error, show a prominent warning card instead of the timeline */}
      {error ? (
        <div className="text-left border border-red-900/30 rounded-xl bg-red-950/20 p-5 mb-6 text-sm text-red-200">
          <p className="font-medium mb-1">Error Encountered</p>
          <p className="text-red-300/80 text-xs leading-relaxed mb-4">{error}</p>
          <button
            type="button"
            onClick={() => navigate("/configure")}
            className="w-full bg-red-900/40 hover:bg-red-900/60 text-red-200 border border-red-700/40 rounded-lg py-2 text-xs font-medium transition-colors"
          >
            ← Go Back & Try Again
          </button>
        </div>
      ) : (
        <>
          <div className="text-left border border-border rounded-xl bg-surface divide-y divide-border overflow-hidden">
            {STEP_LABELS.map((label, i) => {
              const state = i < stepIndex ? "done" : i === stepIndex ? "active" : "pending";
              return (
                <div key={label} className="flex items-center gap-3 px-4 py-3.5">
                  <span
                    className={`w-5 h-5 rounded-full flex items-center justify-center text-[11px] font-mono flex-shrink-0 ${
                      state === "done"
                        ? "bg-accent-2 text-bg"
                        : state === "active"
                        ? "border-2 border-accent text-accent animate-pulse"
                        : "border-2 border-border-strong text-text-muted"
                    }`}
                  >
                    {state === "done" ? "✓" : i + 1}
                  </span>
                  <span className={`text-sm ${state === "pending" ? "text-text-muted" : "text-text-primary"}`}>
                    {label} {state === "active" && "..."}
                  </span>
                </div>
              );
            })}
          </div>

          <div className="h-1.5 bg-surface-2 rounded-full overflow-hidden mt-6">
            <div
              className="h-full bg-accent transition-all duration-500 ease-out"
              style={{ width: `${progress}%` }}
            />
          </div>
          
          <p className="text-[11px] font-mono text-text-muted mt-3">
            Progress: {progress}% · Large videos may take a few minutes to crop.
          </p>
        </>
      )}
    </div>
  );
}